// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ..
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTI1epnYBJzS60PTIF-ZtCGwKM_9d5vM',
    appId: '1:362237849757:web:ebe31fd0d17d1c1b992474',
    messagingSenderId: '362237849757',
    projectId: 'w4-27-7d7e5',
    authDomain: 'w4-27-7d7e5.firebaseapp.com',
    storageBucket: 'w4-27-7d7e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWXHXSjnZV7cP-q22n5jxvD8kvyKhuvE',
    appId: '1:362237849757:android:cd9e9b19df099297992474',
    messagingSenderId: '362237849757',
    projectId: 'w4-27-7d7e5',
    storageBucket: 'w4-27-7d7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYp68kQ9HdruBWuEP6kDxNg5nb6XPF-o',
    appId: '1:362237849757:ios:88acd87695a5e644992474',
    messagingSenderId: '362237849757',
    projectId: 'w4-27-7d7e5',
    storageBucket: 'w4-27-7d7e5.firebasestorage.app',
    iosBundleId: 'com.example.w427Jakkarach',
  );
}
